### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by rajdee** [dsznajder/vscode-es7-javascript-react-snippets#5]
I think that we should have some options for the codestyle code
for example:

- using semicolons
- using single quotes or selecting quotes type

**Comment by dsznajder** [comment]
@rajdee For me it is not a problem as long as you are using VSCode eslint `auto-fix` because it corrects this after save. I can investigate if there is any possibility to change quotes and semicolons for snippets dynamically but I've seen many packages which were just cloned and changed for using semicolons.

**Comment by jimmywongroo** [comment]
Standard.js is not a standard. It's also far less popular and has a much much flatter trends than prettier and plain old eslint.

Please at least put the semicolons back.

https://www.npmtrends.com/standard-vs-eslint-vs-prettier

**Comment by dsznajder** [comment]
@jimmywongroo This package never had semicolons, so I won't bring back anything. As I said on my first comment, you can use auto-fix for adding semicolons inside VSCode config.
